version: "3.7"
services:



  db:
    image: mysql:latest
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    env_file:
      .env
    ports:
      - 3306:3306
    networks:
      - default



  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
        - db
    networks:
      - default



volumes:
  persistent: