version: "3.7"
services:



  db:
    image: mysql:latest
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Vpbest322
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: Vpbest322
    ports:
      - 3306:3306
    networks:
      - default

  app:
    # Собираем из Dockerfile
    build:
      # Корнем указываем корень основного проекта
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: app
    image: digitalocean.com/php
    working_dir: /var/www/app
    # Показываем наружу 80 порт
    ports:
      - "8080:8080"
    # Подключаем к общей сети с другими контейнерами
    networks:
      - default
    volumes:
      - "../app:/var/www/app"
      - "../docker:/var/www/docker"
      - "../migrations:/var/www/migrations"
      - "../php/local.ini:/usr/local/etc/php/conf.d/local.ini"

volumes:
  persistent: