version: "3.7"
services:



  db:
    image: mysql:latest
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    container_name: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - default

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    image: digitalocean.com/php
    working_dir: /var/www/app
    depends_on:
      - db
    ports:
      - ${APP_PORT}:8080
    networks:
      - default
    volumes:
      - "../app:/var/www/app"
      - "../docker:/var/www/docker"
      - "../migrations:/var/www/migrations"
volumes:
  persistent: