name: PHP Code Sniffer

on:
  pull_request:
    branches-ignore:
      - dev

jobs:
  phpcs:
    name: Run PHP CodeSniffer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Fetch base ref
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: phpcs
